In [1]:
import pandas as pd

data = {"eng":['b','c','a','d']}
df = pd.DataFrame(data)
print(type(df))
df

<class 'pandas.core.frame.DataFrame'>


eng
0   b
1   c
2   a
3   d

In [2]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [3]:
print(type(df.values))
df.values[1]

<class 'numpy.ndarray'>


array(['c'], dtype=object)

In [6]:
encoder_x = LabelEncoder()
df['lbl_encoder'] = encoder_x.fit_transform(df['eng']) ## sklearn fit_transform으로 하나의 함수를 구현해놨다
df

eng  lbl_encoder
0   b            1
1   c            2
2   a            0
3   d            3

In [8]:
val = df['lbl_encoder']
new_val = val.values
print(new_val.shape)
n = new_val.reshape(-1,1)
n.shape ##2차원으로 변경해주어야함

(4,)


(4, 1)

In [10]:
onehot = OneHotEncoder()
val = df['lbl_encoder'].values.reshape(-1,1)
y = onehot.fit_transform(val).toarray()
print(y)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]]


In [11]:
onehot_val = pd.DataFrame(y,dtype=int)
onehot_val

0  1  2  3
0  0  1  0  0
1  0  0  1  0
2  1  0  0  0
3  0  0  0  1

In [12]:
df_new = pd.concat([df,onehot_val],axis=1)
df_new

eng  lbl_encoder  0  1  2  3
0   b            1  0  1  0  0
1   c            2  0  0  1  0
2   a            0  1  0  0  0
3   d            3  0  0  0  1

In [26]:
data2 = {"eng2":['MS','Google','Google','Apple']}
df2 = pd.DataFrame(data2)

In [27]:
encoder_x2 = LabelEncoder()
df2['enco'] = encoder_x2.fit_transform(df2['eng2'])
df2

eng2  enco
0      MS     2
1  Google     1
2  Google     1
3   Apple     0

In [28]:
val2 = df2['enco']
new_val2 = val2.values
n2 = new_val2.reshape(-1,1)

In [29]:
onehot = OneHotEncoder()
val2 = df2['enco'].values.reshape(-1,1)
y2 = onehot.fit_transform(val).toarray()
y2

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.]])

In [30]:
onehot_val = pd.DataFrame(y2,dtype=int)
onehot_val

0  1  2  3
0  0  1  0  0
1  0  0  1  0
2  1  0  0  0
3  0  0  0  1

In [31]:
df2_new = pd.concat([df2,onehot_val],axis=1)
df2_new

eng2  enco  0  1  2  3
0      MS     2  0  1  0  0
1  Google     1  0  0  1  0
2  Google     1  1  0  0  0
3   Apple     0  0  0  0  1