In [1]:
from sklearn import model_selection
from sklearn.model_selection import train_test_split
from PIL import Image
import os, glob
import numpy as np
from keras.preprocessing.image import ImageDataGenerator, load_img
from keras.utils import to_categorical
from sklearn.model_selection import train_test_split
import pandas as pd

Using TensorFlow backend.
C:\Users\Seoul IT\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\Seoul IT\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\Seoul IT\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\Seoul IT\anaconda3\lib\site-packages\tensorflow\python\framewo

In [36]:


print(os.getcwd())
## 분류 데이터 로딩

#%%
root_dir = "./food_test_after/"
# 카테고리 명령 지정 (1)
categories = ["갈비구이","갈비탕",'갈치구이','감자채볶음','계란찜','김밥','김치찌개','깻잎장아찌','꼬막찜',
                  '된장찌개','떡볶이','만두','물회','배추김치','삼계탕','새우튀김','소세지볶음','수정과',
                  '순대','식혜','약과','육회','자장면','족발','찜닭','콩자반','피자','한과','해물찜','후라이드치킨']
nb_classes = len(categories)

# 이미지 크기 지정 (2)
image_width = 128
image_height = 128
IMAGE_CHANNELS=3

#%%

## 데이터 변수
X = [] # 이미지 데이터
Y = [] # 레이블 데이터

#cat =[]
#data2 = []

df = pd.DataFrame.from_records([{'filename':'data','category':'category'}])

for idx, category in enumerate(categories):
    image_dir = root_dir + category
    files = glob.glob(image_dir + "/" + "*.jpg")
    print(image_dir + "/" +"*.jpg")
    # print(files)
    for i, f in enumerate(files):
        # 이미지 로딩 (3)
        img = Image.open(f)
        img = img.convert("RGB")
        img = img.resize((image_width, image_height))
        data = np.asarray(img)
        #df_cat = pd.DataFrame.from_records([{'filename':f,'category':category}])
        #join = pd.concat(df,df_cat)
        #df.append(df_cat)
        #cat.append(category)
        #data2.append(data)
        X.append(data)
        Y.append(idx)

X = np.array(X)
Y = np.array(Y)
print(X)
#%%
# 학습 데이터와 테스트 데이터 나누기 (4)
#X_train, X_test, Y_train, Y_test = train_test_split(X, Y,train_size=0.999)
X_train, X_test, Y_train, Y_test = train_test_split(X, Y,train_size=0.999)
#%%
# 데이터 파일 저장 (5)
np.save(root_dir + "food_test_after_2.npy", xy)


C:\Users\Seoul IT\Documents\Python
./food_test_after/갈비구이/*.jpg
./food_test_after/갈비탕/*.jpg
./food_test_after/갈치구이/*.jpg
./food_test_after/감자채볶음/*.jpg
./food_test_after/계란찜/*.jpg
./food_test_after/김밥/*.jpg
./food_test_after/김치찌개/*.jpg
./food_test_after/깻잎장아찌/*.jpg
./food_test_after/꼬막찜/*.jpg
./food_test_after/된장찌개/*.jpg
./food_test_after/떡볶이/*.jpg
./food_test_after/만두/*.jpg
./food_test_after/물회/*.jpg
./food_test_after/배추김치/*.jpg
./food_test_after/삼계탕/*.jpg
./food_test_after/새우튀김/*.jpg
./food_test_after/소세지볶음/*.jpg
./food_test_after/수정과/*.jpg
./food_test_after/순대/*.jpg
./food_test_after/식혜/*.jpg
./food_test_after/약과/*.jpg
./food_test_after/육회/*.jpg
./food_test_after/자장면/*.jpg
./food_test_after/족발/*.jpg
./food_test_after/찜닭/*.jpg
./food_test_after/콩자반/*.jpg
./food_test_after/피자/*.jpg
./food_test_after/한과/*.jpg
./food_test_after/해물찜/*.jpg
./food_test_after/후라이드치킨/*.jpg
[[[[189 197 200]
   [157 165 168]
   [ 61  69  72]
   ...
   [ 26  26  28]
   [ 26  27  27]
   [ 26  28  27]]

  [[ 52  6

In [ ]:
train_df, validate_df = train_test_split(df, test_size=0.20, random_state=42)

In [41]:
IMAGE_SIZE = (image_width,image_height)
batch_size=15
train_datagen = ImageDataGenerator(
    rotation_range=15,  # 정수 무작위 회전의 각도 범위
    rescale=1./255,     # 크기 재조절. 기본은 None이고 None인 경우 크기 재조절이 안됨.
    shear_range=0.1,    # 부동 소수점. 층밀리기 강도(도 단위의 반시계 방향 층밀리기 각도)
    zoom_range=0.2,     # 부동 소수점.[하한, 상한] 무작위 줌의 범위 [1-zoom_range, 1+zoom_range]
    horizontal_flip=True,  # 인풋을 무작위로 가로로 뒤집기
    width_shift_range=0.1, # 1D 형태의 유사배열 혹은 정수
    height_shift_range=0.1 # 1D 형태의 유사배열 혹은 정수
)


train_generator = train_datagen.flow_from_dataframe(
    X_train,    # 데이터 프레임 
    "/kaggle/working/train_img/train/",   # 이미지 위치 
    x_col='filename',  # 
    y_col='category',  # target 데이터를 갖는 데이터 프레임의 컬럼
    target_size=IMAGE_SIZE,    # 정수의 튜플 (높이, 넓이) 디폴트 값(256, 256) 모든 이미지의 크기 조정.
    class_mode='categorical',  #  "categorical", "binary", "sparse", "input", "other" 중 하나
    batch_size=batch_size      # 데이터 배치의 크기. 배치사이즈
)

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [39]:
print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)

(5602, 128, 128, 3)
(5602,)
(6, 128, 128, 3)


In [ ]:
from sklearn import model_selection
from sklearn.model_selection import train_test_split
from PIL import Image
import os, glob
import numpy as np

print(os.getcwd())
## 분류 데이터 로딩

#%%
root_dir = "./Image_project/kfood/"
# 카테고리 명령 지정 (1)
categories = ["Chicken", "Dolsotbab", "Jeyugbokkeum", "Kimchi", 
                "Samgyeobsal", "SoybeanPasteStew"]
nb_classes = len(categories)

# 이미지 크기 지정 (2)
image_width = 64
image_height = 64

#%%

## 데이터 변수
X = [] # 이미지 데이터
Y = [] # 레이블 데이터

for idx, category in enumerate(categories):
    image_dir = root_dir + category
    files = glob.glob(image_dir + "/" + "*.jpg")
    print(image_dir + "/" +"*.jpg")
    # print(files)
    for i, f in enumerate(files):
        # 이미지 로딩 (3)
        img = Image.open(f)
        img = img.convert("RGB")
        img = img.resize((image_width, image_height))
        data = np.asarray(img)
        X.append(data)
        Y.append(idx)

X = np.array(X)
Y = np.array(Y)
print(X)
#%%
# 학습 데이터와 테스트 데이터 나누기 (4)
X_train, X_test, Y_train, Y_test = train_test_split(X, Y)

#%%
xy = (X_train, X_test, Y_train, Y_test)
# 데이터 파일 저장 (5)
np.save(root_dir + "kfood.npy", xy)